### ISSUE TITLE
maintenance tasks

### ISSUE THREAD

**Issue by belm0** [python-trio/purerpc#32]
The purerpc repo was transferred to python-trio.  Here are the short-term tasks I'm intending, with the goal of pushing a maintenance release to pypi for active dependees that may be having problems with the old anyio 1.x dependency of this package:
  * [x] note on README crediting original author, explain that the project is in maintenance mode (keep things working for active dependees), point to https://github.com/grpc/grpc for people needing asyncio only
  * [x] misc: doc updates, TODO's I noted while walking through the code, prune unused imports
  * [x] set up CI (travis-ci.org is defunct, use github actions), pin requirements for reproducible tests
  * [x] **upgrade to anyio 3.x.  It does imply that curio support will be dropped.**  Related to the upgrade, `Server.serve()` will be strongly discouraged in favor of a newly-added `Server.serve_async()`.  PR #33
  * [x] drop Python 3.5 and 3.6 support - they are past end of life, and it's a large burden to the implementation verbosity and performance (async_generator shim, etc.) 
  * [x] remove runtime patching of `anyio.run()`.  This was to support `backend="uvloop"` (`run()` already supports `use_uvloop` backend-specific option, use the correct way) and the `PURERPC_BACKEND` environment variable (introduce something like `purerpc_run()`).
  * [x] **tag release and push to pypi**

**Comment by standy66** [comment]
I also seem to have used private APIs like `anyio._networking` and `anyio._get_async_lib()` back then to get around some issues. I guess we should get rid of this to maintain better compatibility.

Also, maybe there is a way we can get rid of [hyper-h2 monkey patches](https://github.com/python-trio/purerpc/blob/master/src/purerpc/grpclib/_h2_monkeypatch.py)?

**Comment by belm0** [comment]
additionally:  drop Python 3.5 and 3.6 support, since they are past end of life, and it's a large burden to the implementation verbosity and performance (async_generator shim, etc.)

**Comment by belm0** [comment]
released v0.7.0
